### ISSUE TITLE
"Add 5" Button Not Visible Vera

### ISSUE THREAD

**Issue by PablaV** [toggledbits/Switchboard-Vera#1]
Running V 1.9 Develop-21104 and the "add 5" button that mentioned in the Read Me is not present. Just the "Create New Virtual Device" button is only there. Running on Vera Plus FW 7.32 Beta 2. Multiple hard refreshes have been done as well. 
![image](https://user-images.githubusercontent.com/82848440/115898618-9b7d9f80-a412-11eb-8916-ef96aa033bcf.png)

**Comment by toggledbits** [comment]
That's a documentation error. The "Add 5" button has not been in Switchboard since it grew to create more types than just switches (a Very Long Time). Nobody reads the docs, so you get the prize. I'll fix the README.
